### ISSUE TITLE
Error: unable to access jarfile automation-0.0.1.jar 

### ISSUE THREAD

**Issue by drittich** [saiscode/kheera#1]
Using Windows 10, when I run `gradlew.bat build` the build and sample test work correctly. When running the Hello World step #3, though:

`java -jar automation-0.0.1.jar -Dproject=GITHUB -Dbrowser=CHROME -Denvironment=PROD -Dsettings=Settings.properties --tags @SEARCH_DEMO --glue in.ramachandr.automation.core.DefaultStepDefs src/main/resources`

I get the following error:

`Error: Unable to access jarfile automation-0.0.1.jar`

**Comment by saiscode** [comment]
Were you able to run the gradle build which creates the jar and also runs the default Github Search?

I'll take a look in a bit at this error.

**Comment by saiscode** [comment]
Can you pull the latest changes and retry? I'm now creating a fat jar to pull all the dependencies into a single jar.

**Comment by saiscode** [comment]
I'm going to close this issue. Can reopen if the fix doesn't work.
